# Generated by Django 4.2.29 on 2026-06-29 11:02

import core.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0068_issue_cached_display_title_a11y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cached_display_title_a11y_ar',
            field=models.CharField(blank=True, editable=False, help_text='Autogenerated cache of the accessible display format of an issue title', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='cached_display_title_ar',
            field=models.CharField(blank=True, editable=False, help_text='Autogenerated cache of the display format of an issue title', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='contact_info_ar',
            field=core.model_utils.JanewayBleachField(blank=True, null=True, verbose_name='Contact Information'),
        ),
    ]
