# Generated by Django 4.2.29 on 2026-06-29 11:02

import core.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_merge_20260603_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='name_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='role_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='editorialgroup',
            name='description_ar',
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editorialgroup',
            name='name_ar',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='settingvalue',
            name='value_ar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
