# Generated by Django 4.2.29 on 2026-06-29 11:02

import core.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0011_fix_news_item_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnewsitem',
            name='body_ar',
            field=core.model_utils.JanewayBleachField(null=True),
        ),
        migrations.AddField(
            model_name='historicalnewsitem',
            name='custom_byline_ar',
            field=models.CharField(blank=True, help_text='If you want a custom byline add it here. This will overwrite the display of the user who created the news item with whatever text is added here.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalnewsitem',
            name='title_ar',
            field=core.model_utils.JanewayBleachCharField(null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='body_ar',
            field=core.model_utils.JanewayBleachField(null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='custom_byline_ar',
            field=models.CharField(blank=True, help_text='If you want a custom byline add it here. This will overwrite the display of the user who created the news item with whatever text is added here.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_ar',
            field=core.model_utils.JanewayBleachCharField(null=True),
        ),
    ]
